<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Smoke_CriticalFlow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a6188a69-7f1e-4620-8eb5-0859af7f8ec4</testSuiteGuid>
   <testCaseLink>
      <guid>880ac1bf-321e-4a96-ac51-4e27b15bd696</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>c4b59831-d74a-4b64-9b3e-5ae23bcae619</id>
         <masked>false</masked>
         <name>var_username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Common/TC_Auth_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;standard_user&quot;</value>
         <variableId>c4b59831-d74a-4b64-9b3e-5ae23bcae619</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;secret_sauce&quot;</value>
         <variableId>28a25a43-b7bc-4242-972f-cf21398f66a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;success&quot;</value>
         <variableId>74cb35f6-d2c8-4dff-abe7-86989fbf257a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e0aa6b-6d6d-4ec8-ba9e-83d0dc8daae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a474a3c-eda6-41cd-b673-0c43da3fc553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/TC_Inventory_DisplayProducts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>24211167-642b-4ea8-8c2e-e9fd1d44d945</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/TC_Auth_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
